server:
  port: 10051
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.25.242.174:3306/erabbit_data?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


# Mybatis 配 置
mybatis-plus:
  # 配 置 扫 描
  mapper-locations: classpath:**/xml/**.xml
  # 别 名 扫 描
  type-aliases-package: com.erabbit.user.pojo;
  # 日 志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

